### ISSUE TITLE
Build errors with current version of RTRlib

### ISSUE THREAD

**Issue by salsh** [rtrlib/python-binding#9]
While building the python binding several errors occur. It seems that some functions do not match the current API of the RTRLib.

**Comment by mroethke** [comment]
should be fixed with 02ee05dfbe84904ce0857e639e807ab81a03d79b on master

**Comment by salsh** [comment]
The build process still throws several errors. The ```rtr_init``` function expects the modified argument list:

```
build/temp.linux-x86_64-2.7/_rtrlib.c:2543:47: error: incompatible type for argument 8 of ‘rtr_init’
   return rtr_init(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9);
                                               ^~
In file included from /usr/local/include/rtrlib/pfx/pfx.h:22:0,
                 from /usr/local/include/rtrlib/rtr_mgr.h:35,
                 from /usr/local/include/rtrlib/rtrlib.h:20,
                 from build/temp.linux-x86_64-2.7/_rtrlib.c:493:
/usr/local/include/rtrlib/rtr/rtr.h:190:5: note: expected ‘enum interval_mode’ but argument is of type ‘void (*)(const struct rtr_socket *, enum rtr_socket_state,  void *, void *)’
 int rtr_init(struct rtr_socket *rtr_socket, struct tr_socket *tr_socket, struct pfx_table *pfx_table,
     ^~~~~~~~
build/temp.linux-x86_64-2.7/_rtrlib.c:2543:10: error: too few arguments to function ‘rtr_init’
   return rtr_init(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9);
```

**Comment by mroethke** [comment]
You are using current master, right? Any reason for not using the latest release?

**Comment by salsh** [comment]
Yes, I used the current master. With the last release it works indeed, thank you!
